version: '3.8'
services:
  dream-league-finance-api:
    build:
      context: .
      target: development
    environment:
      POSTGRES_HOST: dream-league-finance-api-postgres
    ports:
      - "3001:3001"
      - "9230:9229"
    command: >
      sh -c "
        npm run migrate &&
        npm run seed &&
        npm run start:watch"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./scripts:/home/node/scripts
    depends_on:
      - dream-league-finance-api-postgres

  dream-league-finance-api-postgres:
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

